### PR TITLE
fix: darkmode not work with git-markdown-css

### PR DESCRIPTION
**Pull request by ZreXoc**
- modify `github-markdown.css` since it isn't compatible with nuxt-colormode (https://github.com/sindresorhus/github-markdown-css/issues/104)
- enable code highlight

### CODE REVIEW

**Comment by rewired-gh** [comment]
Thank you for the contribution. But before moving on with this PR, some details may need to be double checked.

Are these changes necessary and have been followed the best practices? It seems that GitHub Markdown style is no longer imported from the npm registry, which might not be a good idea.

Also, the `!important` things *might* be removed and implemented by a more elegant approach.

As far as I can recall, the current Nuxt prose style looks pretty promising and comes with syntax highlight, which suggests that the GitHub Markdown style thing could completely removed. This may be the best practice.

Best regards

**Comment by rewired-gh** [comment]
Could you please provide the detailed steps to reproduce the issue? I was unable to reproduce the problem on the main branch.

**Comment by longlin10086** [comment]
截屏2024-11-01 22 01 03
Well, this bug happens on page: https://mirrors.osa.moe/news/new-frontend

**Comment by rewired-gh** [comment]
> 截屏2024-11-01 22 01 03 Well, this bug happens on page: https://mirrors.osa.moe/news/new-frontend

The bug is not related to a specific page.

**Comment by rewired-gh** [comment]
I can reproduce the issue. It may be due to the differences between the Nuxt color scheme and the system preference color scheme.

**Comment by rewired-gh** [comment]
The issue was fixed by other means. Thanks for the contribution. This PR will be closed.

I would suggest that open an issue for discussion before starting to implement the fix in future occasions.

**Pull request closed without merging**
